[package]
name = "tar-get"
version = "0.1.0"
edition = "2024"
description = "Serialize a vector of objects to disk, then start deserilizing them in constant time."

[dependencies]
serde = "1"
thiserror = "2"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1"
